# Generated by Django 2.1.2 on 2018-12-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='success',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='unsuccess',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='dateTest',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='dateView',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='time',
        ),
        migrations.AddField(
            model_name='statistic',
            name='statistic_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistic',
            name='statistic_success',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='statistic_unsuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.TextField(max_length=500),
        ),
    ]
