# Generated by Django 2.1.2 on 2018-12-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20181209_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='time',
            field=models.TimeField(default=0.0),
        ),
    ]
