# Generated by Django 2.1.2 on 2018-12-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_topic_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='time',
        ),
    ]
