# Generated by Django 2.1.2 on 2018-12-13 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_topic_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='card_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Card'),
        ),
    ]
