# Generated by Django 2.1.2 on 2018-12-08 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('success', models.IntegerField(default=0)),
                ('unsuccess', models.IntegerField(default=0)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Card')),
            ],
            options={
                'db_table': 'statictic',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('time', models.TimeField(default=0)),
                ('dateView', models.DateField(default=0)),
                ('dateTest', models.DateField(default=0)),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Topic'),
        ),
    ]
